[versions]
kotlin = "2.1.21"
ktor = "3.1.3"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mavencentral = { id = "io.github.hfhbd.mavencentral", version = "0.0.17" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
binary = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
